# Generated by Django 5.1 on 2025-10-08 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Для колец - внутренний диаметр, для круглых изделий - диаметр', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Диаметр (мм)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Реальная высота изделия в миллиметрах', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Высота (мм)'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference_photo_type',
            field=models.CharField(choices=[('ear', '👂 Серьги (на ухе)'), ('finger', '💍 Кольцо (на пальце)'), ('wrist', '⌚ Браслет (на запястье)'), ('neck', '📿 Колье/Подвеска (на шее)'), ('none', 'Без эталона')], default='none', help_text='Выберите тип фото для отображения размеров', max_length=20, verbose_name='Тип эталонного фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_ruler',
            field=models.BooleanField(default=False, help_text='Отображать интерактивную линейку на странице товара', verbose_name='Показывать линейку'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Реальная ширина изделия в миллиметрах', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Ширина (мм)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Фото на фоне эталона (ухо, рука, шея)', verbose_name='Эталонное фото'),
        ),
    ]
