# Generated by Django 5.1 on 2025-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_diameter_mm_product_height_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('ear', '👂 Ухо'), ('finger', '💍 Палец'), ('wrist', '⌚ Запястье'), ('neck', '📿 Шея')], max_length=20, unique=True, verbose_name='Тип эталона')),
                ('image', models.ImageField(upload_to='reference_images/', verbose_name='Эталонное изображение')),
                ('width_mm', models.DecimalField(decimal_places=1, help_text='Реальная ширина эталонного изображения', max_digits=6, verbose_name='Ширина эталона (мм)')),
                ('height_mm', models.DecimalField(decimal_places=1, help_text='Реальная высота эталонного изображения', max_digits=6, verbose_name='Высота эталона (мм)')),
                ('description', models.TextField(blank=True, help_text='Описание эталона для производителей', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Эталонное изображение',
                'verbose_name_plural': 'Эталонные изображения',
                'ordering': ['reference_type'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='editor_data',
            field=models.TextField(blank=True, help_text='JSON с координатами и масштабом', verbose_name='Данные редактора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для колец - рассчитывается автоматически', max_digits=6, null=True, verbose_name='Диаметр (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Рассчитывается автоматически при подгонке', max_digits=6, null=True, verbose_name='Высота (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference_photo_type',
            field=models.CharField(choices=[('ear', '👂 Серьги'), ('finger', '💍 Кольцо'), ('wrist', '⌚ Браслет'), ('neck', '📿 Колье/Подвеска'), ('none', 'Без эталона')], default='none', help_text='Выберите тип для подгонки под эталон', max_length=20, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_ruler',
            field=models.BooleanField(default=True, help_text='Отображать интерактивную линейку на странице товара', verbose_name='Показывать линейку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Рассчитывается автоматически при подгонке', max_digits=6, null=True, verbose_name='Ширина (мм)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Фото с подогнанным изделием (используется редактором)', verbose_name='Эталонное фото'),
        ),
    ]
