# Generated by Django 5.1 on 2025-10-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_referenceimage_product_editor_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
