# Generated by Django 5.1 on 2025-10-16 18:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Покрытие',
                'verbose_name_plural': 'Покрытия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('precious', 'Драгоценные камни'), ('semi_precious', 'Полудрагоценные камни'), ('organic', 'Органические материалы'), ('synthetic', 'Синтетические/Неминеральные')], max_length=20, verbose_name='Категория вставки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип вставки',
                'verbose_name_plural': 'Типы вставок',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Цвет металла',
                'verbose_name_plural': 'Цвета металлов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stone_description',
            new_name='insert_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_stones',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 16, 18, 52, 27, 863547, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to='catalog.factory', verbose_name='Создана заводом'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_inserts',
            field=models.BooleanField(default=False, verbose_name='Наличие вставок'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_stamp',
            field=models.BooleanField(default=False, verbose_name='Наличие клейма'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_brand',
            field=models.CharField(blank=True, max_length=200, verbose_name='Производитель/Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Масса металла (г)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stamp_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание клейма'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Общая масса изделия (г)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро')], max_length=20, verbose_name='Тип материала'),
        ),
        migrations.AddField(
            model_name='product',
            name='coatings',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.coating', verbose_name='Покрытия'),
        ),
        migrations.AddField(
            model_name='product',
            name='insert_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.inserttype', verbose_name='Типы вставок'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.metalcolor', verbose_name='Цвет металла'),
        ),
        migrations.CreateModel(
            name='Purity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро')], max_length=20, verbose_name='Тип металла')),
                ('value', models.CharField(max_length=20, verbose_name='Значение пробы')),
                ('system', models.CharField(choices=[('metric', 'Метрическая'), ('carat', 'Каратная')], default='metric', max_length=20, verbose_name='Система проб')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проба',
                'verbose_name_plural': 'Пробы',
                'ordering': ['material_type', '-value'],
                'unique_together': {('material_type', 'value', 'system')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='purity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.purity', verbose_name='Проба'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.style', verbose_name='Стиль'),
        ),
    ]
