# Generated by Django 5.1 on 2025-10-22 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_coating_inserttype_metalcolor_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Масса чистого металла без вставок', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Масса металла (г)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Масса всего изделия со всеми вставками', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Общая масса изделия (г)'),
        ),
    ]
