# Generated by Django 5.1 on 2025-11-11 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_metal_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('light_primary', models.CharField(default='#6366f1', max_length=7, verbose_name='Primary (светлая)')),
                ('light_secondary', models.CharField(default='#8b5cf6', max_length=7, verbose_name='Secondary (светлая)')),
                ('light_background', models.CharField(default='#ffffff', max_length=7, verbose_name='Background (светлая)')),
                ('light_surface', models.CharField(default='#f9fafb', max_length=7, verbose_name='Surface (светлая)')),
                ('light_text', models.CharField(default='#111827', max_length=7, verbose_name='Text (светлая)')),
                ('light_border', models.CharField(default='#e5e7eb', max_length=7, verbose_name='Border (светлая)')),
                ('dark_primary', models.CharField(default='#6366f1', max_length=7, verbose_name='Primary (тёмная)')),
                ('dark_secondary', models.CharField(default='#8b5cf6', max_length=7, verbose_name='Secondary (тёмная)')),
                ('dark_background', models.CharField(default='#1f2937', max_length=7, verbose_name='Background (тёмная)')),
                ('dark_surface', models.CharField(default='#374151', max_length=7, verbose_name='Surface (тёмная)')),
                ('dark_text', models.CharField(default='#ffffff', max_length=7, verbose_name='Text (тёмная)')),
                ('dark_border', models.CharField(default='#4b5563', max_length=7, verbose_name='Border (тёмная)')),
                ('success_color', models.CharField(default='#10b981', max_length=7, verbose_name='Success')),
                ('danger_color', models.CharField(default='#ef4444', max_length=7, verbose_name='Danger')),
                ('warning_color', models.CharField(default='#f59e0b', max_length=7, verbose_name='Warning')),
                ('info_color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Info')),
                ('gradient_enabled', models.BooleanField(default=True, verbose_name='Градиент включен')),
                ('gradient_start', models.CharField(blank=True, max_length=7, verbose_name='Начало градиента')),
                ('gradient_end', models.CharField(blank=True, max_length=7, verbose_name='Конец градиента')),
                ('gradient_angle', models.IntegerField(default=135, verbose_name='Угол градиента')),
                ('google_fonts_url', models.URLField(blank=True, verbose_name='Google Fonts URL')),
                ('font_family', models.CharField(blank=True, max_length=100, verbose_name='Семейство шрифтов')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активная тема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
