# Generated by Django 5.1 on 2025-11-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='gradient_angle',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='gradient_end',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='gradient_start',
        ),
    ]
