# Generated by Django 5.1 on 2025-11-12 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_theme_gradient_angle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='theme',
            name='color_scheme',
            field=models.CharField(blank=True, default='indigo', max_length=20, verbose_name='Цветовая схема'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Тема по умолчанию'),
        ),
        migrations.AddField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(default='#6366f1', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(default='#8b5cf6', max_length=7, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название темы'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='theme',
            name='danger_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='dark_background',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='dark_border',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='dark_primary',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='dark_secondary',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='dark_surface',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='dark_text',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='google_fonts_url',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='info_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='light_background',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='light_border',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='light_primary',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='light_secondary',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='light_surface',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='light_text',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='success_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='warning_color',
        ),
    ]
