# Generated by Django 5.1 on 2025-11-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_theme_options_alter_theme_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='sharp_corners',
            field=models.BooleanField(default=False, verbose_name='Острые углы'),
        ),
    ]
