# Generated by Django 5.1 on 2025-11-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_theme_sharp_corners'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='body_font',
            field=models.CharField(default='Inter', help_text='Шрифт для обычного текста', max_length=50, verbose_name='Шрифт основного текста'),
        ),
        migrations.AddField(
            model_name='theme',
            name='heading_font',
            field=models.CharField(default='Playfair Display', help_text='Шрифт для h1, h2, h3, h4, h5, h6', max_length=50, verbose_name='Шрифт заголовков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference_photo_type',
            field=models.CharField(choices=[('ear', '👂 Ухо/Серьги'), ('finger', '💍 Палец/Кольцо'), ('wrist', '⌚ Запястье/Браслет'), ('neck', '📿 Шея/Колье'), ('none', 'Без эталона')], default='none', help_text='Выберите тип для подгонки под эталон', max_length=20, verbose_name='Тип изделия'),
        ),
        migrations.AlterField(
            model_name='referenceimage',
            name='reference_type',
            field=models.CharField(choices=[('ear', '👂 Ухо/Серьги'), ('finger', '💍 Палец/Кольцо'), ('wrist', '⌚ Запястье/Браслет'), ('neck', '📿 Шея/Колье')], max_length=20, unique=True, verbose_name='Тип эталона'),
        ),
    ]
