# Generated by Django 5.1 on 2025-11-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_theme_body_font_theme_heading_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='body_font_weight',
            field=models.CharField(default='400', help_text='Например: 400, 500, 600', max_length=4, verbose_name='Толщина шрифта текста'),
        ),
        migrations.AddField(
            model_name='theme',
            name='heading_font_weight',
            field=models.CharField(default='700', help_text='Например: 400, 700, 900', max_length=4, verbose_name='Толщина шрифта заголовков'),
        ),
    ]
