# Generated by Django 5.1 on 2025-12-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_theme_body_font_weight_theme_heading_font_weight'),
    ]

    operations = [
        # Индексы для оптимизации фильтрации в каталоге
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'is_active'], name='catalog_pro_price_a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', 'is_active'], name='catalog_pro_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'is_active'], name='catalog_pro_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['material', 'purity', 'is_active'], name='catalog_pro_mat_pur_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['metal_color', 'is_active'], name='catalog_pro_color_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['style', 'is_active'], name='catalog_pro_style_idx'),
        ),

        # Индексы для Category
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='catalog_cat_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_idx'),
        ),

        # Индекс для Factory
        migrations.AddIndex(
            model_name='factory',
            index=models.Index(fields=['is_verified', '-created_at'], name='catalog_fac_verified_idx'),
        ),
    ]
