# Generated by Django 5.1 on 2025-12-14 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название списка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, verbose_name='Список по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Список избранного',
                'verbose_name_plural': 'Списки избранного',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='factory',
            name='catalog_fac_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_price_a_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_mat_pur_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_color_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_style_idx',
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.favoritelist', verbose_name='Список избранного'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product', 'favorite_list')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritelist',
            unique_together={('user', 'name')},
        ),
    ]
